version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: CEE-SISTEMA-CONTAINER
    ports: 
      - 4410:4410
    volumes: 
      - .:/home/node/app